apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp # any key value can be used (eg mylabel: bar)
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
