apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  ports:
    - name: http
      port: 80
      nodePort: 30080 # this is a restriction by K8's we cant use ports under 30000
  selector:
    release: 0-5
  # See the documentation to get startet with loadbalancers
  # https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access
  # type: LoadBalencer
  type: NodePort
